type IMovie = {
    _id: string,
    name: string,
    launchDate: string,
    director: string,
    actors: string,
    image: string,
    whereToWatch: string,
    category: string,
    type: string,
}

export const moviesData: IMovie[] = [
    {
        _id: "6582eba7ca5a62d6851d18ab1",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab2",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab3",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab4",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab5",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab6",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab7",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab8",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    },
    {
        _id: "6582eba7ca5a62d6851d18ab9",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    }, {
        _id: "6582eba7ca5a62d6851d18ab0",
        name: "Avengers",
        launchDate: "20/12/2020",
        director: "Russo Brothers",
        actors: "RDJ, Chris Evans, Tom Hidleston",
        image: "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
        whereToWatch: "Theathers, Disney+",
        category: "Action",
        type: "movie",
    }
]